apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-code-service
  namespace: codeservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: covid-code-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid-code-service
    spec:
      containers:
      - image: "registry.nosi.cv/na_nos_mon/covidcodeservice:$BUILD_NUMBER"
        imagePullPolicy: IfNotPresent
        name: covid-code-service
        ports:
        - containerPort: 8113
          name: covid-code-service
          protocol: TCP
      imagePullSecrets:
      - name: nanosmon
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
