authcodegeneration:
  jwt:
    issuer: "http://172.18.50.36:8080/auth/realms/cv-covid-code"
    token-validity: 300000
    privateKey: ""
  monitor:
    prometheus:
      user: "prometheus"
      password: "todo"
  service:
    keycloak:
      realm: "cv-covid-code"
      uri: "http://172.18.50.35:8080/auth/"
      masterPassword: "Passs0rd"
      clientSecret: "73632134-4c52-42ef-b781-7832782e3ac8"

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://172.18.50.35:8080/auth/realms/cv-covid-code"

ha-authcode-generation-service:
  allowed-origin: "http://172.18.50.35:4200"
