authcodegeneration:
  jwt:
    issuer: "https://identity-r.bit.admin.ch/realms/bag-pts"
    token-validity: 300000
    privateKey: ${vcap.services.signingKey_dev.credentials.privateKey}
  monitor:
    prometheus:
      user: "prometheus"
      password: ${vcap.services.ha_prometheus_dev.credentials.password}

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://identity-r.bit.admin.ch/realms/bag-pts"

ha-authcode-generation-service:
  allowed-origin: "https://www.covidcode-d.admin.ch"
