authcodegeneration:
  jwt:
    issuer: "http://172.18.50.36:8080/auth/realms/cv-covid-code"
    token-validity: 300000
    privateKey: ""
  monitor:
    prometheus:
      user: "prometheus"
      password: "todo"
  service:
    keycloak:
      realm: "cv-covid-code"
      uri: "http://172.18.50.38:8080/auth/"
      masterPassword: "Pa55w0rd"
      clientSecret: "fc4a5716-a097-47ad-b58f-6184cd1e0ffa"

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://172.18.50.35:8080/auth/realms/cv-covid-code"

ha-authcode-generation-service:
  allowed-origin: "http://172.18.50.35:4200"
