  
logging:
  level:
    ch:
      admin:
        bit:
          jeap: INFO
        bag: INFO

authcodegeneration:
  jwt:
    issuer: "https://identity.bit.admin.ch/realms/bag-pts"
    token-validity: 300000
    privateKey: ${vcap.services.signingKey_prod.credentials.privateKey}
  monitor:
    prometheus:
      user: "prometheus"
      password: ${vcap.services.ha_prometheus_prod.credentials.password}

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://identity.bit.admin.ch/realms/bag-pts"

ha-authcode-generation-service:
  allowed-origin: "https://www.covidcode.admin.ch"
