version: '3'
services:
  db-authcodegeneration:
    image: postgres
    ports:
      - "3113:5432"
    environment:
      - POSTGRES_USER=haauthcodegeneration
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=haauthcodegeneration
